name: Rust

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      blogdb:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: blog_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          # Opens port 3306 on service container and host
          # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
          - 3306:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        ROCKET_CONFIG: .github/Rocket.test.toml
      run: |
        cargo install diesel_cli
        diesel migration run --database-url mysql://root:root@blogdb:3306/blog_test
        cargo test --verbose
